// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace CodeLab.UI.Web.Mvc.Areas.Jquery.Controllers {
    public partial class ImageRotatorController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ImageRotatorController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ImageRotatorController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ImageRotatorController Actions { get { return MVC.Jquery.ImageRotator; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Jquery";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ImageRotator";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ImageRotator";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string TryIt = "TryIt";
            public readonly string GetImagesAndDesc = "GetImagesAndDesc";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Index = "Index";
            public const string TryIt = "TryIt";
            public const string GetImagesAndDesc = "GetImagesAndDesc";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Index = "~/Areas/Jquery/Views/ImageRotator/Index.cshtml";
            public readonly string TryIt = "~/Areas/Jquery/Views/ImageRotator/TryIt.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ImageRotatorController: CodeLab.UI.Web.Mvc.Areas.Jquery.Controllers.ImageRotatorController {
        public T4MVC_ImageRotatorController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TryIt() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.TryIt);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetImagesAndDesc() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetImagesAndDesc);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
